---
include:
  - remote: 'https://github.com/karthiksatchitanand/litmus/raw/master/gitlab/pod-templates/pod-failure-template.yml'

stages:
  #- buildApp
  - appDeploy
  - chaosInfraSetup
  - chaosChartPull
  #- chaosInject
  - chaosInfraCleanup
  #- production

#Build:
#  stage: build
#  script: 
#    - <abc>

Deploy to Staging:
  stage: appDeploy
  image: ksatchit/gitlab-runner:ci
  script:
    - kubectl apply -f ./sample_apps/nginx/stateless/nginx.yml 
    - kubectl apply -f ./sample_apps/nginx/stateless/rbac.yaml 

Setup Chaos Infra:
  stage: chaosInfraSetup
  image: ksatchit/gitlab-runner:ci
  script: 
    - helm repo add chaos-charts https://litmuschaos.github.io/chaos-charts
    - helm repo update
    - helm install --name=litmus chaos-charts/litmus --namespace=litmus 
  
Install Chaos Charts:
  stage: chaosChartPull
  image: ksatchit/gitlab-runner:ci
  script: 
    - kubectl apply -f https://raw.githubusercontent.com/litmuschaos/community-charts/master/charts/kubernetes/state/experiments/container-kill-exp.v0.1.0.yaml 
 
#Inject Pod Failure Chaos:
#  stage: chaos
#  extends: .pod_failure_template
#  before_script:
#  variables:
#    app_ns: default
#    app_label: "app=nginx"
   
Cleanup Chaos Infra:
  stage: chaosInfraCleanup
  image: ksatchit/gitlab-runner:ci
  script: 
    - helm repo update
    - helm delete litmus --purge  
