---
include:
  - remote: 'https://github.com/karthiksatchitanand/litmus/raw/master/gitlab/pod-templates/pod-failure-template.yml'

stages:
  #- build
  #- test
  - staging
  - chaos
  #- production

#Build:
#  stage: build
#  script: 
#    - <abc>

#Test:
#  stage: test
#  script: 
#    - <def>

Deploy to Staging:
  # this will be app developer's custom gitlab runner image
  # typically this stage will have artifact dependencies (kubeconfig)
  # we have hard-burned it 

  image: ksatchit/appci:gitlab
  stage: staging
  script:
    - cp /admin.conf ~/.kube/config
    - kubectl apply -f ./sample_apps/nginx/stateless/nginx.yml --kubeconfig=/root/.kube/config 
     
Inject Pod Failure Chaos:
  stage: chaos
  extends: .pod_failure_template
  before_script:
    - cp /admin.conf ~/.kube/config
  variables:
    app_ns: default
    app_label: "app=nginx"
   
  
