---
include:
  - remote: 'https://github.com/karthiksatchitanand/litmus/raw/master/gitlab/pod-templates/pod-failure-template.yml'

stages:
  #- buildApp
  - appDeploy
  - chaosInfraSetup
  - chaosChartPull
  #- chaosInject
  - chaosInfraCleanup
  #- production

#Build:
#  stage: build
#  script: 
#    - <abc>

Deploy to Staging:
  stage: appDeploy
  image: ksatchit/gitlab-runner:ci
  script:
    - kubectl apply -f ./sample_apps/nginx/stateless/nginx.yml 
    - kubectl apply -f ./sample_apps/nginx/stateless/rbac.yaml 

Setup Chaos Infra:
  stage: chaosInfraSetup
  image: ksatchit/gitlab-runner:ci
  script:
    - ./hack/helm_setup chaos-charts https://litmuschaos.github.io/chaos-charts
    - helm install --name=litmus chaos-charts/litmus --namespace=litmus 
  
Install Chaos Charts:
  stage: chaosChartPull
  image: ksatchit/gitlab-runner:ci
  script:
    - ./hack/helm_setup chaos-charts https://litmuschaos.github.io/chaos-charts
    - helm install --name=chaos-experiments chaos-charts/kubernetes  

#Inject Pod Failure Chaos:
#  stage: chaos
#  extends: .pod_failure_template
#  before_script:
#  variables:
#    app_ns: default
#    app_label: "app=nginx"
   
Cleanup Chaos Infra:
  stage: chaosInfraCleanup
  image: ksatchit/gitlab-runner:ci
  script: 
    #- kubectl delete ns litmus 
    #- kubectl delete crds chaosengines.litmuschaos.io chaosexperiments.litmuschaos.io chaosresults.litmuschaos.io litmusresults.litmus.io
    - helm version
    - helm delete litmus --purge 
    - helm delete chaos-experiments --purge
  when: always
