dist: trusty
sudo: required
install: true
language: go
go:
  - 1.11.2
env:
  global:
    - GOARCH=amd64
before_install:
  - sleep 15
  - sudo apt-get install -y
  - sudo apt-get install -y curl
script:
  - make
