---
# Source: openebs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "litmusInfra.fullname" . }}
  labels:
    name: {{ include "litmusInfra.name" . }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
