---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litmusInfra.fullname" . }}
  namespace: {{ include "litmusInfra.name" . }}
  labels:
    name: {{ include "litmusInfra.name" . }}
