---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:   
    metadata:
      labels:
        app: nginx
      annotations:
         litmus.io/chaos: "true"
         litmus.io/experiment: "disappearing-targets"
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-vol
      volumes:
        - name: nginx-vol
          persistentVolumeClaim:
            claimName: nginx-vol-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-vol-claim
spec:
  storageClassName: openebs-standalone
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G

  

  
