version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: | 
          docker build . -f alpine-netcat/Dockerfile.alpine -t ksatchit/alpine-netcat:latest 
          docker save -o workspace/image.tar ksatchit/alpine-netcat:latest 
      - persist_to_workspace:
          root: workspace
          paths: 
            - image.tar
  push:
    machine: 
      image: circleci/classic:201808-01
    steps: 
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: |
          docker load -i /tmp/workspace/image.tar
          docker login -u "${DNAME}" -p "${DPASS}";
          docker push ksatchit/alpine-netcat:latest

  release: 
    machine: 
      image: circleci/classic:201808-01
    steps: 
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - run: |
          docker load -i /tmp/workspace/image.tar
          image_id=$( docker images -q ksatchit/alpine-netcat:latest )
          docker login -u "${DNAME}" -p "${DPASS}";
          docker tag ${image_id} ksatchit/alpine-netcat:${CIRCLE_TAG}
          docker push ksatchit/alpine-netcat:${CIRCLE_TAG}
        
workflows:
  version: 2
  operator_build_deploy:
    jobs:
      - build
      - push:
          requires:
            - build
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

