apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: chaosoperator.v0.5.0
  namespace: default 
  annotations:
    capabilities: Basic Install
    categories: "Developer Tools"
    containerImage: index.docker.io/litmuschaos/chaos-operator:ci
    createdAt: 2019-07-15T10:28:08Z
    repository: https://github.com/litmuschaos/chaos-operator
    certified: "false"
    support: https://slack.openebs.io/
    alm-examples: |
    description: Chaos Engineering for Kubernetes 
spec:
  displayName: Litmus
  description: >
    **Litmus** is a chaos engineering framework for Kubernetes

    # Start using Litmus
    
    * Refer the [docs](https://docs.litmuschaos.io)
    
    # Contribute to Litmus

    * To learn how to contribute, please read the contribution guide: 
      [contribution guide](https://github.com/litmuschaos/litmus/blob/master/CONTRIBUTING.md)

    # Community

    * Litmus welcomes your feedback and contributions in any form possible.
      [Join our Community](https://openebs.io/join-our-slack-community)
    
  keywords:
    - Litmus
    - ChaosEngineering
  version: 0.5.0
  maturity: alpha
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: MayaData
  links:
    - name: Litmus Website
      url: https://litmuschaos.io
    - name: Source Code
      url: https://github.com/litmuschaos
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAKkAAACpCAYAAABQ1R0vAAADfUlEQVR4nOzdMW4cZRiA4dkoAjosUVASiQY6d4iO3IR0iAo6Cg4BN4CahgNEin0BWGoKAuIASxMgzY9W2ghhCVm21/O/Tp7nAPN9Wr36Z2eySe6PMRYouzd7AbiMSMkTKXkiJe/+jKGbzcbT2ktgjLFZY46TlDyRkidS8kRKnkjJEyl5IiVPpOSJlDyRkidS8kRKnkjJEyl5IiVPpORN+dHzTXzwyafL7198eaNrvP/Xn8vj99492k7cLicpeSIlT6TkiZQ8kZInUvJESp5IyRMpeSIlT6TkiZQ8kZInUvJESp5IyRMpeSIlT6TkiZQ8kZInUvJESp5IyRMpeSIlT6TkiZQ8kZInUvJESp5IyRMpeSIlT6TkiZQ8kZInUvJESp5IyRMpeSIlT6TkiZQ8kZInUvLu3H8l/vpvT5fv3n7rRtf4+ccflsdH24jbducivffs2fLhG6/d6BrPn/99tH24fW735ImUPJGSJ1LyREqeSMkTKXkiJU+k5ImUPJGSJ1LyREqeSMkTKXkiJU+k5ImUPJGSJ1LyREqeSMkTKXkiJU+k5ImUPJGSJ1LyREqeSMkTKXkiJU+k5ImUPJGSJ1LyREqeSMkTKXkiJU+k5ImUPJGSJ1LyREqeSMkTKXkiJU+k5ImUPJGSJ1LyREqeSMm7P3uBu+bk5GQ5PT2dvcZRbLfbZbfbzV7jUiK9on2gT548mb3GUTx8+HA5Ozubvcal3O7JEyl5IiVPpOSJlDyRkidS8kRKnkjJEyl5IiVPpOSJlDyRkidS8u7c70l3u91yfn5+o2tst9up8yvuwg+e9zZjjPWHbjbrD+XoxhibNea43ZMnUvJESp5Iua5f1xokUq7r6VqDZkX6crzDebVd/z3eFc2K9PtJczme1f7C/qz3pA+WZfll9cEcyx9jjJO1hk05SccY++8z386YzVF8teawKSfp8u9puv9e8+aUBbiu/VP96RhjtT9TnfZ0fzhNP5s1n2v7eM1Al9mvoMYY3yzL8vXMHbiSR2OM1f+Fs+nvSccY+9P089l7cKlHh0NlddO+k1602Ww+WpZl/yG8M3sX/uOnwy1+tfeiF00/SV/Y30bGGPuHqUeHD4a5zg+n5+nMQJfSSXrR4el/f7o+mL3LK2Yf5PbwYJuQjRReyNzu4f+IlDyRkidS8kRKnkjJEyl5IiXvnwAAAP//eI+ULPfWFXEAAAAASUVORK5CYII= 
      mediatype: image/png
  labels:
    alm-owner-openebs: chaosoperator
    operated-by: chaosoperator
  selector:
    matchLabels:
      alm-owner-openebs: chaosoperator
      operated-by: chaosoperator
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
  install:
    strategy: deployment
    spec:
      clusterPermissions:
        - serviceAccountName: chaos-operator
          rules:
            - apiGroups:
              - "*"
              resources:
              - clusterroles
              - clusterrolebindings
              verbs:
              - "*"
            - apiGroups:
              - "*"
              resources:
              - namespaces
              - services
              - serviceaccounts
              - pods
              - deployments
              - daemonsets
              - secrets
              - events
              - endpoints
              - configmaps
              - jobs
              verbs:
              - create
              - get
              - list
              - watch
              - update
              - patch
              - delete
            - apiGroups:
              - apiextensions.k8s.io
              resources:
              - customresourcedefinitions
              verbs:
              - create
              - get
              - list
              - update
              - patch
              - delete 
            - apiGroups:
              - admissionregistration.k8s.io
              resources:
              - validatingwebhookconfigurations
              verbs:
              - create
              - get
              - list
              - watch
              - update
              - patch
              - delete 
            - apiGroups:
              - openebs.io
              resources:
              - openebsinstalltemplates
              - openebsinstalltemplates/finalizers
              - openebsinstalltemplates/status
              verbs:
              - create
              - get
              - list
              - watch
              - patch
              - update
              - delete
      deployments:
        - name: chaos-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: chaos-operator
            strategy:
              type: RollingUpdate
            template:
              metadata:
                labels:
                  name: chaos-operator
                name: chaos-operator
              spec:
                containers:
                - name: chaos-operator
                  image: index.docker.io/litmuschaos/helm-operator:ci
                  imagePullPolicy: Always
                  env:
                  - name: WATCH_NAMESPACE
                    value: ""
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
                  - name: OPERATOR_NAME
                    value: "chaos-operator"
                serviceAccountName: chaos-operator
  customresourcedefinitions:
    owned:
      - name: chaosengines.litmuschaos.io
        version: v1alpha1
        kind: ChaosEngine
        displayName: ChaosEngine
        description: Represents the Chaos Schedule for an application
        resources:
          - kind: ServiceAccount
            name: ''
            version: v1
          - kind: ClusterRole
            name: ''
            version: rbac.authorization.k8s.io/v1beta1
          - kind: ClusterRoleBinding
            name: ''
            version: rbac.authorization.k8s.io/v1beta1
          - kind: Deployment
            name: ''
            version: apps/v1beta1
          - kind: Service
            name: ''
            version: v1
          - kind: ConfigMap
            name: ''
            version: v1
          - kind: DaemonSet
            name: ''
            version: extensions/v1beta1
          - kind: Secret
            name: ''
            version: v1
          - kind: ValidatingWebhookConfiguration
            name: ''
            version: admissionregistration.k8s.io/v1beta1
        specDescriptors:
        statusDescriptors: 

