---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "chaosOperator.fullname" . }}
  labels:
    name: {{ include "chaosOperator.name" . }}
    instance: {{ .Release.Name  }}
    chart: {{ include "chaosOperator.chart" . }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
