---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chaosOperator.fullname" . }}
  labels:
    name: {{ include "chaosOperator.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chaosOperator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "chaosOperator.fullname" . }}
  namespace: {{ .Release.Namespace }}
