---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chaosOperator.fullname" . }}
  labels:
    name: {{ include "chaosOperator.name" . }}
    instance: {{ .Release.Name  }}
    chart: {{ include "chaosOperator.chart" . }}

